name: Tropica
version: ${project.version}
main: me.tecc.tropica.Tropica
api-version: 1.13
authors: [Technotype, MarcusSlover, funtodead]
description: 'Tropica is custom sloverteam survival plugin which will not be public to all github users.'
website: 'https://tecc.me/projects/tropica/'

commands:
  help:
    aliases:
      - helpme
  broadcast:
    aliases:
      - bc
  collection:
    aliases:
      - items
      - collect