name: Tropica
version: ${project.version}
main: me.tecc.tropica.Tropica
api-version: 1.13

commands:
  craft:
    aliases:
      - crafting
      - c
  enderchest:
    aliases:
      - ec
  sethome:
  delhome:
  home:
    aliases:
      - h
  surface: