name: Tropica
version: ${project.version}
main: me.tecc.tropica.Tropica
api-version: 1.13
authors: [Technotype, MarcusSlover, funtodead]
description: Tropica is an open source survival plugin
website: https://tecc.me/projects/tropica/
commands:
  help:
    description:
    usage: /<command>
    aliases:
      - helpme
