name: Tropica
version: ${project.version}
main: me.tecc.tropica.tropica.Tropica
api-version: 1.13
authors: [Technotype, MarcusSlover]
description: Tropica is an open source survival plugin
website: https://tecc.me/projects/tropica/
